menu:
  首页: https://home.yuxiang.ren
  归档: /archives/
  GitHub: https://github.com/shlyren
  推特: https://twitter.com/shlyren
  微博: http://weibo.com/shlyjen  
  关于: /about/
  邮箱: mailto:mail@yuxiang.ren
  谷歌搜索: https://google.yuxiang.ren

favicon: https://source.yuxiang.ren/favicon_yuxiang.ico
logo: https://ww3.sinaimg.cn/large/006tNc79gy1fe3u2mby1ij30400403z5.jpg

# Comment
# e.g disqus: seansun
disqus:
duoshuo: shlyren

# Analytics
# google-analytics:
# ga: UA-65933410-1

# Copyright Infomation
startyear: 2016
