menu:
  首页: /
  归档: /archives/
  GitHub: https://github.com/shlyren
  微博: http://weibo.com/shlyjen
  Google: https://google.yuxiang.ren
  邮箱: mailto:mail@yuxiang.ren
  关于: /about/

favicon: https://renyuxiang.oss-cn-shanghai.aliyuncs.com/yuxiang.ren/favicon.ico
logo: https://ww3.sinaimg.cn/large/006tNc79gy1fe3u2mby1ij30400403z5.jpg

# Comment
# e.g disqus: seansun
#disqus: shlyren
#duoshuo: shlyren

# Analytics
# google-analytics:
# ga: UA-65933410-1

# Copyright Infomation
startyear: 2016
